CLS
COLOR 15, 1
CLS
PRINT "Everytab System/7 Upgrade"
PRINT "-------------------------"
PRINT ""
PRINT ""
PRINT "Welcome to Everytab System/7 Upgrade"
PRINT "This program shall go through the following"
PRINT ""
PRINT "1) Upgrading any ES/7 version on your hard disk or Loading ES/7 on your hard disk which already has DOS"
PRINT ""
PRINT ""
PRINT "Version on this disk - Build 250CE"
PRINT "Press any key to continue"
DO
LOOP UNTIL INKEY$ <> ""

